version: 2

jobs:
  # using tox
  toxify:
      docker:
        - image: circleci/python:3.6
      steps:
        - checkout
        - restore_cache:
           keys:
             - pip_cache_{{ checksum "setup.py" }}
        - run:
            name: Install utils
            command: |
              sudo pip install tox wheel
        - run:
            command: tox
        - save_cache:
            key: pip_cache_{{ checksum "setup.py" }}
            paths:
              - "~/.tox"
workflows:
  version: 2

  build:
    jobs:
      - toxify
